# Reference file paths
ref:
  genome: "resources/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
  gtf: "resources/Homo_sapiens.GRCh38.110.gtf"
  star_index: "resources/star_index"

# Resources (Threads)
threads:
  star: 16
  fastp: 8
  rmats: 8
  fastqc: 2
